---
AWSTemplateFormatVersion: "2010-09-09"

Description: "Application S3 buckets - artifacts, ..."

Parameters:
  EnvType:
    Description: Environment type
    Type: String
    AllowedValues: ["dev", "prod"]
    ConstraintDescription: "Must specify `dev` or `prod`"

Resources:
  ApplicationArtifactsBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "artifacts-${AWS::Region}-${AWS::AccountId}-${EnvType}"

Outputs:
  ArtifactsBucket:
    Description: Artifacts bucket name
    Value: !Ref ApplicationArtifactsBucket
    Export:
      Name: !Sub "${AWS::StackName}-ArtifactsBucket"
