---
AWSTemplateFormatVersion: "2010-09-09"

Description: "Data lake S3 buckets - raw, stage, analytics"

Parameters:
  EnvType:
    Description: Environment type
    Type: String
    AllowedValues: ["dev", "prod"]
    ConstraintDescription: "Must specify `dev` or `prod`"

Conditions:
  IsProduction: !Equals [!Ref EnvType, "prod"]

Resources:
  RawDataLayerBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "raw-${AWS::Region}-${AWS::AccountId}-${EnvType}"
      VersioningConfiguration: !If [IsProduction, {Status: Enabled}, !Ref "AWS::NoValue"]

  StageDataLayerBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "stage-${AWS::Region}-${AWS::AccountId}-${EnvType}"

  AnalyticsDataLayerBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "analytics-${AWS::Region}-${AWS::AccountId}-${EnvType}"
